#+TITLE: Ludum Dare 46

THEME: Keep It Alive

* Game

Set in a natural environment.
We are an entity that goes and maintain and/or repair the nature.
Has an energy that connects with nature, which he doesn't know about at first.

The more the player solves puzzles, or just explores, the more energy he gets.

Pitch : You are a character that goes and explore a forest, accessing unknown places
by clearing out paths, and solving puzzles, which helps get more and more in sync
with his environment as he (unknowlingly at first) helps out the forest.

Pitch V2 : You are a casual hiker, going for a walk in a forest, where you find yourself
exploring hidden areas, and through actions and puzzle-solving, manage to nurse the forest
back to health, from natural and human contamination.


Possible puzzles :
- sokoban?
- move around trunks to clear out a path. trunks only move in straight lines.
- 





* Random game ideas

- maintain something on the long run
    - war
    - hope
    - friendship
    - energy (fire)


- keep :: property, continuity, nurse, immortalize, prolonging, focus
- alive :: continuity, important, organic, creature, human, notions, principals, focus, survival

- narration
tradition
ritual
motor to come out of a difficult situtation
centered on character, or someone else, or something else
ecology

'

puzzle game, rpg

possible constraints:
- not violent

** Gameplay ideas

- fire source as both light source and energy source
the more you use it the more the fire diminishes

- player is an energy source
proximity to machines makes the activate, startup