#+TITLE: Ludum Dare 46

THEME: Keep It Alive

* Game

Set in a natural environment.
We are an entity that goes and maintain and/or repair the nature.
Has an energy that connects with nature, which he doesn't know about at first.

Pitch : You are a character that goes and explore a forest/natural environment, where he can
solve "puzzles" to help/maintain the environment, unlocking new areas to explore.

Possible puzzles :
- 

* Random game ideas

- maintain something on the long run
    - war
    - hope
    - friendship
    - energy (fire)


- keep :: property, continuity, nurse, immortalize, prolonging, focus
- alive :: continuity, important, organic, creature, human, notions, principals, focus, survival

- narration
tradition
ritual
motor to come out of a difficult situtation
centered on character, or someone else, or something else
ecology

'

puzzle game, rpg

possible constraints:
- not violent

** Gameplay ideas

- fire source as both light source and energy source
the more you use it the more the fire diminishes

- player is an energy source
proximity to machines makes the activate, startup